apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch-deployment
  labels:
    configid: elasticsearch-deployment
spec:
  serviceName: "elasticsearch-service-internal"
  replicas: 3
  selector:
    matchLabels:
      configid: elasticsearch-container
  template:
    metadata:
      labels:
        configid: elasticsearch-container
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: component
                      operator: In
                      values:
                        - elasticsearch-container
                topologyKey: kubernetes.io/hostname
      securityContext:
        fsGroup: 1000
      initContainers:
        - name: init-sysctl1
          image: busybox:1.27.2
          command:
            - sysctl
            - -w
            - vm.max_map_count=262144
          securityContext:
            privileged: true
        - name: init-sysctl2
          image: busybox:1.27.2
          command:
            - "chmod"
            - "777"
            - "/usr/share/elasticsearch/data"
          securityContext:
            privileged: true
          volumeMounts:
            - name: es-stateful-volume
              mountPath: /usr/share/elasticsearch/data
      containers:
        - name: elasticsearch
          image: alonana/elasticsearch:1.0.0
          securityContext:
            capabilities:
              add:
                - IPC_LOCK
                - SYS_RESOURCE
          env:
            - name: cluster.name
              value: "elasticsearch"
            - name: node.name
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: bootstrap.memory_lock
              value: "true"
            - name: ES_JAVA_OPTS
              value: "-Xms256m -Xmx256m"
            - name: discovery.zen.ping.unicast.hosts
              value: "elasticsearch-service-internal"
          ports:
            - containerPort: 9200
              name: es-exposed
            - containerPort: 9300
              name: es-internal
          readinessProbe:
            initialDelaySeconds: 60
            timeoutSeconds: 6
            failureThreshold: 20
            successThreshold: 1
            httpGet:
              path: /
              port: 9200
              scheme: HTTP
          livenessProbe:
            timeoutSeconds: 6
            failureThreshold: 10
            successThreshold: 1
            initialDelaySeconds: 60
            httpGet:
              path: /_cluster/health
              port: 9200
              scheme: HTTP
          volumeMounts:
            - name: es-stateful-volume
              mountPath: /usr/share/elasticsearch/data
      volumes:
        - name: es-stateful-volume
          persistentVolumeClaim:
            claimName: es-persistent-volume-claim
