apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch-deployment
  labels:
    configid: elasticsearch-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      configid: elasticsearch-container
  template:
    metadata:
      labels:
        configid: elasticsearch-container
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: component
                      operator: In
                      values:
                        - elasticsearch-container
                topologyKey: kubernetes.io/hostname
      initContainers:
        - name: init-sysctl
          image: busybox:1.27.2
          command:
            - sysctl
            - -w
            - vm.max_map_count=262144
          securityContext:
            privileged: true
      containers:
        - name: elasticsearch
          image: alonana/elasticsearch:1.0.0
          securityContext:
            capabilities:
              add:
                - IPC_LOCK
                - SYS_RESOURCE
          env:
            - name: cluster.name
              value: "elasticsearch"
            - name: bootstrap.memory_lock
              value: "true"
            - name: ES_JAVA_OPTS
              value: "-Xms256m -Xmx256m"
            - name: discovery.zen.ping.unicast.hosts
              value: "elasticsearch-service-internal"
          ports:
            - containerPort: 9200
              name: es-exposed
            - containerPort: 9300
              name: es-internal
          readinessProbe:
            initialDelaySeconds: 60
            timeoutSeconds: 6
            failureThreshold: 20
            successThreshold: 1
            httpGet:
              path: /
              port: 9200
              scheme: HTTP
          livenessProbe:
            timeoutSeconds: 6
            failureThreshold: 10
            successThreshold: 1
            initialDelaySeconds: 60
            httpGet:
              path: /_cluster/health
              port: 9200
              scheme: HTTP

