apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-service-exposed
spec:
  selector:
    configid: elasticsearch-container
  type: NodePort
  ports:
    - port: 443
      targetPort: 443
      nodePort: AK8S_GLOBAL_PORT_ES
      protocol: TCP
      name: es-queries
