apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-service-discovery
  labels:
    configid: elasticsearch-service-discovery
spec:
  selector:
    configid: elasticsearch-container
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true
  ports:
    - name: elasticsearch-discovery
      port: 9300
      targetPort: 9300
      protocol: TCP
