filebeat.inputs:
  - type: docker

    include_lines: ['enforcer output']
#    json.keys_under_root: true
#    json.add_error_key: true
#    json.message_key: keykey
    containers.stream: stdout
    containers.ids:
    - "*"

output.logstash:
  hosts: ["logstash-service.default.svc.cluster.local:5044"]
  ssl.certificate_authorities: ["/etc/securebeat/ca/ca.crt"]
  ssl.certificate: "/etc/securebeat/client/tls.crt"
  ssl.key: "/etc/securebeat/client/tls.key"

logging.level: debug