filebeat.inputs:
  - type: docker
    include_lines: ['enforcer']
#    json.keys_under_root: true
#    json.add_error_key: true
#    json.message_key: keykey
    containers.stream: stdout
    containers.ids:
    - "*"

output.logstash:
  hosts: ["logstash-service:5044"]

logging.level: debug