kind: PersistentVolume
apiVersion: v1
metadata:
  name: es-persistent-volume
  labels:
    configid: es-persistent-volume
spec:
  storageClassName: manual
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/esdata"