apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web
spec:
  selector:
    matchLabels:
      configid: nginx-stateful-container
  serviceName: "nginx-stateful-service"
  replicas: 3
  template:
    metadata:
      labels:
        configid: nginx-stateful-container
    spec:
      containers:
        - name: nginx
          image: k8s.gcr.io/nginx-slim:0.8
          ports:
            - containerPort: 80
              name: web
          volumeMounts:
            - name: nginx-stateful-volume
              mountPath: /usr/share/nginx/html
      volumes:
        - name: nginx-stateful-volume
          persistentVolumeClaim:
            claimName: nginx-persistent-volume-claim
