kind: PersistentVolume
apiVersion: v1
metadata:
  name: nginx-persistent-volume
spec:
  storageClassName: manual
  capacity:
    storage: 10Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"