apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  labels:
    configid: nginx-service
spec:
  selector:
    configid: nginx-container
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001
      protocol: TCP
      name: http
