apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash-deployment
  labels:
    configid: logstash-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      configid: logstash-container
  template:
    metadata:
      labels:
        configid: logstash-container
    spec:
      containers:
        - name: logstash
          image: AK8S_DOCKER_REPOSITORY/logstash:1.0.0
          env:
            - name: ES_USER
              valueFrom:
                secretKeyRef:
                  name: elasticsearch-password-secret
                  key: user
            - name: ES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: elasticsearch-password-secret
                  key: password
          ports:
            - containerPort: 9600
              name: logstash-http
            - containerPort: 5044
              name: logstash-beat
          readinessProbe:
            initialDelaySeconds: 10
            timeoutSeconds: 6
            failureThreshold: 20
            successThreshold: 1
            httpGet:
              path: /
              port: 9600
              scheme: HTTP
          livenessProbe:
            timeoutSeconds: 6
            failureThreshold: 10
            successThreshold: 1
            initialDelaySeconds: 60
            httpGet:
              path: /_cluster/health
              port: 9600
              scheme: HTTP
          volumeMounts:
            - name: logstash-volume
              mountPath: /usr/share/logstash/pipeline/
            - name: securebeat-server-volume
              mountPath: /etc/securebeat/server
            - name: securebeat-ca-volume
              mountPath: /etc/securebeat/ca
            - name: logstash-yml-volume
              mountPath: /usr/share/logstash/config/logstash.yml
              subPath: logstash.yml
      volumes:
        - name: logstash-yml-volume
          configMap:
            name: logstash-yml-config
        - name: logstash-volume
          configMap:
            name: logstash-pipeline
        - name: securebeat-ca-volume
          configMap:
            name: securebeat-ca-config
        - name: securebeat-server-volume
          secret:
            secretName: securebeat-server-secret



