apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash-deployment
  labels:
    configid: logstash-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      configid: logstash-container
  template:
    metadata:
      labels:
        configid: logstash-container
    spec:
      containers:
        - name: logstash
          image: AK8S_DOCKER_REPOSITORY/logstash:1.0.0
          ports:
            - containerPort: 9600
              name: logstash-http
            - containerPort: 5044
              name: logstash-beat
          readinessProbe:
            initialDelaySeconds: 10
            timeoutSeconds: 6
            failureThreshold: 20
            successThreshold: 1
            httpGet:
              path: /
              port: 9600
              scheme: HTTP
          livenessProbe:
            timeoutSeconds: 6
            failureThreshold: 10
            successThreshold: 1
            initialDelaySeconds: 60
            httpGet:
              path: /_cluster/health
              port: 9600
              scheme: HTTP
          volumeMounts:
            - name: logstash-volume
              mountPath: /usr/share/logstash/pipeline/
      volumes:
        - name: logstash-volume
          configMap:
            name: logstash-pipeline



