apiVersion: v1
kind: Service
metadata:
  name: logstash-service
spec:
  selector:
    configid: logstash-container
  type: NodePort
  ports:
    - port: 9600
      targetPort: 9600
      protocol: TCP
      name: logstash-http
    - port: 5044
      targetPort: 5044
      protocol: TCP
      name: logstash-beat
