apiVersion: v1
kind: Service
metadata:
  name: gui-service
spec:
  selector:
    configid: gui-container
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: AK8S_GLOBAL_PORT_GUI
      protocol: TCP
      name: http
