apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: es-persistent-volume-claim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: azurefile
  resources:
    requests:
      storage: 10Mi