apiVersion: apps/v1
kind: Deployment
metadata:
  name: envoy-logrotate-deployment
  labels:
    configid: envoy-logrotate-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      configid: envoy-logrotate-container
  template:
    metadata:
      labels:
        configid: envoy-logrotate-container
    spec:
      shareProcessNamespace: true
      containers:
        - name: envoy
          image: AK8S_DOCKER_REPOSITORY/envoy-logrotate:1.0.0
          ports:
            - containerPort: 10000
              name: envoy-in
          volumeMounts:
            - name: envoy-volume
              mountPath: /etc/envoy/
            - name: logs-volume
              mountPath: /logs
        - name: logrotate
          image: AK8S_DOCKER_REPOSITORY/logrotate:1.0.0
          volumeMounts:
            - name: logs-volume
              mountPath: /logs
      volumes:
        - name: envoy-volume
          configMap:
            name: envoy-logrotate-config
        - name: logs-volume
          hostPath:
            path: /logs
