apiVersion: v1
kind: Service
metadata:
  name: logstash-service
  labels:
    configid: logstash-service
spec:
  selector:
    configid: logstash-container
  type: NodePort
  ports:
    - port: 9600
      targetPort: 9600
      nodePort: 30003
      protocol: TCP
      name: logstash-in
